### ISSUE TITLE
--schema_only doesn't work with empty tables

### ISSUE THREAD

**Issue by lathonez** [lathonez/clone-row#2]
```
2015-08-12 11:08:58 inserting a minimal row into target database..
Traceback (most recent call last):
  File "/Users/stephen/code/mysql-clone-row/CloneRow.py", line 611, in <module>
    DOLLY.insert_target()
  File "/Users/stephen/code/mysql-clone-row/CloneRow.py", line 428, in insert_target
    cur.execute(insert_sql, (self.database['filter'],))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'None' in 'field list'")
```

It'll be cause we're doing select \* limit 1 to get the columns.

**Comment by lathonez** [comment]
Also it's trying to do an insert on schema_only (in this case), which will fail but is dangerous.
